CREATE TABLE "CURRENCY"(
    "ID" CHARACTER VARYING(32) NOT NULL,
    "CREATE_DATETIME" TIMESTAMP,
    "CURRENCY_CODE" CHARACTER VARYING(16) NOT NULL,
    "CURRENCY_NAME" CHARACTER VARYING(64) NOT NULL,
    "IS_DELETE" BOOLEAN,
    "UPDATE_DATETIME" TIMESTAMP
);

ALTER TABLE "CURRENCY" ADD CONSTRAINT "CONSTRAINT_5" PRIMARY KEY("ID");

ALTER TABLE "CURRENCY" ADD CONSTRAINT "UK_7N17YGAJJCHSSO2N0LYXRSYIF" UNIQUE("CURRENCY_CODE");